#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 Horst Birthelmer.  All Rights Reserved.
#
# FS QA Test 780
#
# test atomic open (file create) and negative dentry open
#
. ./common/preamble
_begin_fstest auto

# Override the default cleanup function.
# _cleanup()
# {
# 	cd /
# 	rm -r -f $tmp.*
# }

# Import common functions.
# . ./common/filter


_supported_fs fuse
_require_test
_require_scratch

srcdir=/tmp/src
mkdir -p $srcdir

d_low=$srcdir/test_file
#make sure file is not there
rm -f $d_low

_scratch_mount "-o source=$srcdir"
echo 'content of the test_file' > $SCRATCH_MNT/test_file
_scratch_unmount
_scratch_mount "-o source=$srcdir"
cat $SCRATCH_MNT/test_file
echo "Silence is golden"
status=0
exit

# optional stuff if your test has verbose output to help resolve problems
#echo
#echo "If failure, check $seqres.full (this) and $seqres.full.ok (reference)"

