#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 Horst Birthelmer.  All Rights Reserved.
#
# FS QA Test 731
#
# atomic open revalidate underlying change
#
. ./common/preamble
_begin_fstest auto

# Override the default cleanup function.
# _cleanup()
# {
# 	cd /
# 	rm -r -f $tmp.*
# }

# Import common functions.
# . ./common/filter


_supported_fs fuse
_require_test
_require_scratch

srcdir=/tmp/src
mkdir -p $srcdir

s_file=$srcdir/test_file
d_file=$SCRATCH_MNT/test_file

_scratch_mount "-o source=$srcdir"
echo "atod" > $d_file
rm -f $s_file
str="b"
echo "$str" > $s_file
reval=$(cat $d_file)
if [ "$str" != "$reval" ]; then
  echo "String mismatch"
  echo "written $str and read $reval"
  exit 1
fi
rm -f $d_file

echo "Silence is golden"
status=0
exit

# success, all done
status=0
exit
